/**
 * Service types shown in provider registration — keep in sync with RegisterForm
 * and All Services filters. Subcategories match the public Home hub category lists.
 */
export interface RegistrationServiceCategory {
  readonly name: string;
  readonly subcategories: readonly string[];
}

export const REGISTRATION_SERVICE_CATEGORIES: readonly RegistrationServiceCategory[] = [
  {
    name: "Home Maintenance",
    subcategories: [
      "Plumbing",
      "Electrical",
      "Carpentry",
      "General Repairs",
      "Door & Window Repair",
      "Furniture Assembly",
      "TV Mounting",
      "Roofing",
      "Flooring",
      "HVAC Services",
      "Handyman Services",
      "Lock Installation",
      "Shelf Installation",
      "Cabinet Installation",
      "Light Fixture Installation",
    ],
  },
  {
    name: "Cleaning Services",
    subcategories: [
      "Residential Cleaning",
      "Carpet Washing",
      "Pest Control",
      "Deep Cleaning",
      "Move-in/Move-out Cleaning",
      "Post-Construction Cleaning",
      "Window Cleaning",
      "Office Cleaning",
      "Upholstery Cleaning",
      "Appliance Cleaning",
      "Gutter Cleaning",
      "Pressure Washing",
      "Green Cleaning",
      "Sanitization Services",
      "Event Cleanup",
      "Regular Maintenance",
    ],
  },
  {
    name: "Appliance Repair",
    subcategories: [
      "Refrigerator Repair",
      "AC Repair",
      "Washing Machine Repair",
      "Dryer Repair",
      "Dishwasher Repair",
      "Oven Repair",
      "Microwave Repair",
      "Water Heater Repair",
      "Garbage Disposal Repair",
      "Ice Maker Repair",
      "Stove Repair",
      "Freezer Repair",
      "Appliance Installation",
      "Appliance Maintenance",
      "Emergency Repair",
      "Warranty Service",
    ],
  },
  {
    name: "Personal Care",
    subcategories: [
      "Babysitting",
      "Nanny Services",
      "Elderly Care",
      "Pet Care",
      "Personal Assistant",
      "Companion Care",
      "Special Needs Care",
      "Overnight Care",
      "Tutoring Services",
      "After School Care",
      "Weekend Care",
      "Holiday Care",
      "Travel Companion",
      "Medical Appointment Assistance",
      "Meal Preparation",
      "Medication Reminders",
    ],
  },
  {
    name: "Housemaid Services",
    subcategories: [
      "Regular Housekeeping",
      "Deep Cleaning",
      "Laundry Services",
      "Cooking Services",
      "Meal Preparation",
      "Grocery Shopping",
      "Organizing Services",
      "Window Cleaning",
      "Ironing Services",
      "Dishwashing",
      "Vacuuming",
      "Mopping",
      "Dusting",
      "Bathroom Cleaning",
      "Kitchen Cleaning",
      "Daily Maintenance",
    ],
  },
  {
    name: "Hotel & Lounge Services",
    subcategories: [
      "Room Service",
      "Concierge",
      "Housekeeping",
      "Event Planning",
      "Catering",
      "Spa Services",
      "Front Desk",
      "Guest Services",
      "Bartending",
      "Waitressing",
      "VIP Services",
      "Reception Services",
      "Security Services",
      "Valet Services",
      "Bell Services",
      "Guest Relations",
    ],
  },
] as const;
